### ISSUE TITLE
Enable discussions on this repo

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/templates#11]
Since this repo now has a discussion issue, I think it's a good time to enable actual discussions to properly segment the issues and discussions. While I agree discussions shouldn't be enabled until they're needed, that time when they are needed is upon us.

I don't have the power to do this directly. Only @danielbraun89 can do this.

**Comment by jcbhmr** [comment]
@danielbraun89 📫

**Comment by danielbraun89** [comment]
done
