### ISSUE TITLE
Enable GitHub Pages deployment from GitHub Actions

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/templates#18]
![image](https://user-images.githubusercontent.com/61068799/217346408-7f3d187e-ad25-4291-a609-4a2d2b5fc0e5.png)

This would let the site deploy successfully. (Hopefully. Assuming all other CI config works.)

This SO answer https://stackoverflow.com/questions/73937666/configure-github-pages-failed indicates that this error means GitHub Pages deployments are not set to GitHub Actions.

![image](https://user-images.githubusercontent.com/61068799/217349262-8d218e44-4ee3-4443-ace1-9db85f7c797b.png)

@danielbraun89

**Comment by danielbraun89** [comment]
Done

**Comment by jcbhmr** [comment]
/re @danielbraun89 

Awesome! 👍 Check out the deployment on GitHub Pages https://devcontainers-contrib.github.io/templates/
