### ISSUE TITLE
Add templates for...

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/templates#5]
<details>
  <summary>The current official devcontainers/templates repo has the following templates:</summary>

- alpine
- anaconda-postgres
- anaconda
- cpp-mariadb
- cpp
- debian
- docker-existing-docker-compose
- docker-existing-dockerfile
- docker-in-docker
- docker-outside-of-docker-compose
- docker-outside-of-docker
- dotnet-fsharp
- dotnet-mssql
- dotnet-postgres
- dotnet
- go-postgres
- go
- java-postgres
- java
- javascript-node-mongo
- javascript-node-postgres
- javascript-node
- jekyll
- kubernetes-helm-minikube
- kubernetes-helm
- markdown
- miniconda-postgres
- miniconda
- php-mariadb
- php
- postgres
- powershell
- python
- ruby-rails-postgres
- ruby
- rust-postgres
- rust
- typescript-node
- ubuntu
- universal

</details>

Here's some other templates that I think would be good to have:
- [ ] deno: Includes [Deno] runtime (_could_ have accompanying image)
- [ ] haskell: Includes the [Haskell toolchain] (_could_ have accompanying image)
- [ ] eleventy: Devcontainer with preset `npm i -g @11ty/eleventy`

Some other ideas for things (non-specific) that could also be added:
- Other static site generators
- Any other images if we ever create a devcontainers-contrib/images repo

_Looking for other template ideas to add to this list!_

[devcontainers/templates]: https://github.com/devcontainers/templates#reademe
[deno]: https://deno.land/
[haskell toolchain]: https://www.haskell.org/downloads/

**Comment by eitsupi** [comment]
> * deno: Includes [Deno](https://deno.land/) runtime (needs accompanying image!)

I think you don't need pre-built images because Deno installs (by Dev Container Features) so fast.
Deno is released so often so managing images may be a challenge.
Check out Julia's case. microsoft/vscode-dev-containers#1114

> * hugo: Devcontainer with `sudo apt install hugo`

The apt-installed Hugo is outdated; the Dev Container Feature for Hugo already exists and should be sufficient.

**Comment by jcbhmr** [comment]
/re @eitsupi

> The apt-installed Hugo is outdated; the Dev Container Feature for Hugo already exists and should be sufficient.

You're absolutely right. 🤦‍♂️ I completely skipped over the Hugo template. I removed it from my list 👍

> I think you don't need pre-built images because Deno installs (by Dev Container Features) so fast.
Deno is released so often so managing images may be a challenge.
> Check out Julia's case. https://github.com/microsoft/vscode-dev-containers/issues/1114

I, _personally_ like the idea of using images for "base presets" and then features to add tools to your existing toolbox... But yeah, I agree that it might be a challenge. More discussion would be welcome.
```

**Comment by eitsupi** [comment]
> I, _personally_ like the idea of using images for "base presets" and then features to add tools to your existing toolbox... But yeah, I agree that it might be a challenge. More discussion would be welcome.

Sorry for my lack of explanation.
I meant that since Templates can include Dev Container Features, it may be sufficient for the Deno template to be the base image (e.g. `mcr.microsoft.com/devcontainers/base:debian`) and a Deno Dev Container Feature.
